// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelAI.Data;

#nullable disable

namespace TravelAI.Migrations
{
    [DbContext(typeof(TravelAIContext))]
    [Migration("20260903013548_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelAI.Models.Atividade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Detalhes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DiaItinerarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HoraFim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraInicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiaItinerarioId");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("TravelAI.Models.DiaItinerario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ItinerarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumeroDia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItinerarioId");

                    b.ToTable("DiasItinerario");
                });

            modelBuilder.Entity("TravelAI.Models.Itinerario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.Property<Guid>("ViagemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ViagemId");

                    b.ToTable("Itinerarios");
                });

            modelBuilder.Entity("TravelAI.Models.PrevisaoTempo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Condicao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DiaItinerarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("ProbabilidadePrecipitacao")
                        .HasColumnType("real");

                    b.Property<float>("TempMax")
                        .HasColumnType("real");

                    b.Property<float>("TempMin")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DiaItinerarioId")
                        .IsUnique();

                    b.ToTable("PrevisoesTempo");
                });

            modelBuilder.Entity("TravelAI.Models.Viagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("NumViajantes")
                        .HasColumnType("int");

                    b.Property<decimal>("Orcamento")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Viagens");
                });

            modelBuilder.Entity("TravelAI.Models.Atividade", b =>
                {
                    b.HasOne("TravelAI.Models.DiaItinerario", "DiaItinerario")
                        .WithMany("Atividades")
                        .HasForeignKey("DiaItinerarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaItinerario");
                });

            modelBuilder.Entity("TravelAI.Models.DiaItinerario", b =>
                {
                    b.HasOne("TravelAI.Models.Itinerario", "Itinerario")
                        .WithMany("Dias")
                        .HasForeignKey("ItinerarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Itinerario");
                });

            modelBuilder.Entity("TravelAI.Models.Itinerario", b =>
                {
                    b.HasOne("TravelAI.Models.Viagem", "Viagem")
                        .WithMany("Itinerarios")
                        .HasForeignKey("ViagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("TravelAI.Models.PrevisaoTempo", b =>
                {
                    b.HasOne("TravelAI.Models.DiaItinerario", "DiaItinerario")
                        .WithOne("PrevisaoTempo")
                        .HasForeignKey("TravelAI.Models.PrevisaoTempo", "DiaItinerarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaItinerario");
                });

            modelBuilder.Entity("TravelAI.Models.DiaItinerario", b =>
                {
                    b.Navigation("Atividades");

                    b.Navigation("PrevisaoTempo");
                });

            modelBuilder.Entity("TravelAI.Models.Itinerario", b =>
                {
                    b.Navigation("Dias");
                });

            modelBuilder.Entity("TravelAI.Models.Viagem", b =>
                {
                    b.Navigation("Itinerarios");
                });
#pragma warning restore 612, 618
        }
    }
}
